language: csharp
dist: xenial
mono: none
sudo: required
services:
  - docker
script:
  - docker build -t build-core-sdk-3.0.100-preview2-alpine3.8:latest .
  - docker run --rm -it --name build-core-sdk-3.0.100-preview2-alpine3.8 build-core-sdk-3.0.100-preview2-alpine3.8:latest